replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: latest

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

environment: development
