apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Build and deploy demo-app
on:
  push:
    branches:
      - "**"
env:
  APP_NAME: demo-app
  BUILD: false
jobs:
  build:
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1

      - name: Handle safe directory errors
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory '*'
        if: $BUILD

      - name: Install dependencies
        uses: docker://golang:1.20
        run: go mod download
        if: $BUILD

      - name: Run tests
        uses: docker://golang:1.20
        run: go test -v ./...
        if: $BUILD
        
      - name: Run build
        uses: docker://golang:1.20
        run: go build -v -buildvcs=false
        if: $BUILD

      - name: Configure container registry credentials
        id: dockerconfig
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: $BUILD
      
      - name: Build and push container
        uses: cloudbees-io/kaniko@v1
        with:
          dockerfile: Dockerfile
          context: .
          destination: ${{ secrets.DOCKERHUB_USER }}/${{ env.APP_NAME }}:${{ cloudbees.scm.sha }}
          labels: maintainer=Greg Maxey,version=${{ cloudbees.scm.sha }}
        if: $BUILD

      - name: Add kubectl config file
        uses: docker://alpine:latest
        run: |
          echo Testing