apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Build and deploy demo-app
on:
  push:
    branches:
      - "**"
env:
  APP_NAME: demo-app
  BUILD: "false"
  DEPLOY: "true"
jobs:
  build:
    if: "false"
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1
      - name: Handle safe directory errors
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory '*'
      - name: Install dependencies
        uses: docker://golang:1.20
        run: go mod download
      - name: Run tests
        uses: docker://golang:1.20
        run: go test -v ./...
      - name: Run build
        uses: docker://golang:1.20
        run: go build -v -buildvcs=false
      - name: Configure container registry credentials
        id: dockerconfig
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push container
        uses: cloudbees-io/kaniko@v1
        with:
          dockerfile: Dockerfile
          context: .
          destination: ${{ secrets.DOCKERHUB_USER }}/${{ env.APP_NAME }}:${{
            cloudbees.scm.sha }}
          labels: maintainer=Greg Maxey,version=${{ cloudbees.scm.sha }}
  deploy:
    if: "true"
    environment: qa
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Checkout code
      - uses: docker://alpine:latest
        name: Add kubectl config.json file
        run: >
          rm -rf ${HOME}/.kube
          mkdir ${HOME}/.kube && cat >> ${HOME}/.kube/config.json << EOF
          ${{ secrets.mlcbMultilinePass }}
          EOF
      - name: Google Cloud authentication and deployment
        uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        run: |
          gcloud auth login --cred-file=${HOME}/.kube/config.json 
          gcloud config set project mlcbplatformproject
          gcloud container clusters get-credentials mlcb-platform-cluster-ap001 --region us-east1 --project mlcbplatformproject 
          kubectl create deployment deployment-mlcb --image=us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
          kubectl expose deployment deployment-mlcb --type LoadBalancer --port 80 --target-port 8080
          kubectl get pods
          kubectl get service deployment-mlcb
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        name: test connection
        run: kubectl get namespaces
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        name: Create target namespace
        run: kubectl create namespace qa
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        name: Deploy helm chart
        kind: deploy
        run: helm install demo-app ./chart -f values.yaml
    needs:
      - build
