apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Build and deploy demo-app
on:
  workflow_dispatch:
env:
  APP_NAME: demo-app
jobs:
  build:
    outputs:
      image-tag: ${{ cloudbees.scm.sha }}
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1
      - name: Handle safe directory errors
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory '*'
      - name: Install dependencies
        uses: docker://golang:1.20
        run: go mod download
      - name: Run tests
        uses: docker://golang:1.20
        run: go test -v ./...
      - name: Run build
        uses: docker://golang:1.20
        run: go build -v -buildvcs=false
      - name: Configure container registry credentials
        id: dockerconfig
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push container
        uses: cloudbees-io/kaniko@v1
        with:
          dockerfile: Dockerfile
          context: .
          destination: ${{ secrets.DOCKERHUB_USER }}/${{ env.APP_NAME }}:${{
            cloudbees.scm.sha }}
          labels: maintainer=Greg Maxey,version=${{ cloudbees.scm.sha }}
  deploy:
    environment: gpm-prod
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Checkout code
      - uses: docker://alpine:latest
        name: Add kubectl config.json file
        run: |
          cat >> gconfig.json << EOF
          ${{ secrets.mlcbMultilinePass }}
          EOF
      - name: Google Cloud authentication
        uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        run: >
          gcloud auth login --cred-file=gconfig.json 

          gcloud container clusters get-credentials mlcb-platform-cluster-ap002 --region us-east1 --project mlcbplatformproject
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        name: test connection
        run: |
          kubectl get namespaces
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        name: Deploy helm chart
        kind: deploy
        run: >
          helm upgrade -i demo-app ./chart -f values.yaml --set
          image.tag=${{needs.build.outputs.image-tag}} --wait 
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        name: Instructions
        run: >
          export SERVICE_IP=$(kubectl get svc --namespace default demo-app
          --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{
          end }}")  

          echo http://$SERVICE_IP        
    needs:
      - build
