apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Build demo-app
on:
  push:
    branches:
      - "**"
env:
  APP_NAME: demo-app
jobs:
  build:
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1

      - name: Install dependencies
        uses: docker://golang:1.20
        run: go mod download

      - name: Run tests
        uses: docker://golang:1.20
        run: go test -v ./...
        
      - name: Run build
        uses: docker://golang:1.20
        run: go build -v

      - name: Create Docker Authentication file
        uses: docker/login-action@v2
        run: echo {"auths":{"hub.docker.com":{"username":"$DOCKERHUB_USER","password":"$DOCKERHUB_TOKEN","auth":"$(
echo $DOCKERHUB_USER:$DOCKERHUB_TOKEN|base64)"}}} >> ${HOME}/.docker/config.json

      - name: Build and push container
        uses: cloudbees-io/kaniko@v1
        with:
          dockerfile: Dockerfile
          context: .
          destination: ${{ secrets.DOCKERHUB_USER }}/${{ env.APP_NAME }}:${{ github.sha }}
          build-args: 
          labels: maintainer=Greg Maxey,version=github.sha
